### ISSUE TITLE
docker setup

### ISSUE THREAD

**Issue by stanthewizzard** [Pondorasti/emojis#10]
Easier to deploy :)
Thanks

**Comment by pondorasti** [comment]
Hey @stanthewizzard, unfortunately I do not have the bandwidth to configure this now. If you or anyone else wants to pick this up, I'm happy to give advice and review the PR.

**Comment by stanthewizzard** [comment]
TBH I'm not able to do that (but install it with compose that I can do)

**Comment by pondorasti** [comment]
sounds good with me, feel free to open a PR if you have anything working and I can take a look
