### ISSUE TITLE
Rate Limiting might need fixing

### ISSUE THREAD

**Issue by gssakash** [Pondorasti/emojis#16]
PROMPT : A reindeer silhouette with a sun at the top shining with an overall dark background

I tried the above prompt against the application and for some reason, it continues going on and on. This would cause problems and take down the server. I think it'll be worthwhile to monitor the rate limiting and maybe even reduce it for one specific session

**Comment by pondorasti** [comment]
I believe there's a small chance for a JWT error that throws unauthorized when submitting creation for emojis. Logs have revealed a small number of those errors that could lead to your issue above. Looking into it.

**Comment by juan13r2facfdvdh** [comment]
![image](https://github.com/Pondorasti/emojis/assets/149821146/c8d53416-e054-4302-81c3-9b9192218bb9)

**Comment by gssakash** [comment]
Looks like this has been completed and can be closed
