### ISSUE TITLE
terms of use

### ISSUE THREAD

**Issue by godetremy** [Pondorasti/emojis#17]
Hello,

What are the licence of generated emoji ?

**Comment by pondorasti** [comment]
will add a license detailing this by tomorrow, thanks for asking

**Comment by pondorasti** [comment]
Just added legal documents as part of https://github.com/Pondorasti/emojis/commit/6164c9358a69c729ca75870c5b66dfd7138afaa1. Here's the tldr of it:

> Free Users: Emojis generated by free users are strictly for personal and non-commercial use.
> Paid Users: Only users with a monthly or yearly subscription can use the generated emojis for commercial purposes.

For the foreseeable future, subscriptions can only be bought from the [mobile app](https://emojis.sh/app).
