### ISSUE TITLE
So many generated but can't see a gallery of created emojis??

### ISSUE THREAD

**Issue by Kiel-H-Byrne** [Pondorasti/emojis#21]
Feature request (i'll try to get a PR in)
gallery of already created emojis w/ fuzzy search

**Comment by pondorasti** [comment]
I've tried getting this done using Prisma's [full text search](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search), but we are blocked on getting it to work with Accelerate, https://github.com/Pondorasti/emojis/pull/28.
