### ISSUE TITLE
Build Failed when deploying

### ISSUE THREAD

**Issue by billythegoat356** [Pondorasti/emojis#24]
The Edge Function "index" size is 1.09 MB and your plan size limit is 1 MB.

**Comment by pondorasti** [comment]
Hi @billythegoat356, unfortunately the repo is not hostable on the Vercel Hobby plan. Because it already relies on Vercel KV and Blob, which will require a Pro plan, there's no incentive to try to optimize the edge function size to fit in the 1MB limit.
