### ISSUE TITLE
Account Access Issues 

### ISSUE THREAD

**Issue by aprilmariebee926** [Pondorasti/emojis#33]
Towhom it may concern :

On  November 30 of 2023,  I purchased a subscription for your platform thru the website at [https://emojis.sh/](https://emojis.sh/) However, despite following the instructions to download the [AI EMOJI APP](https://apps.apple.com/us/app/ai-emojis-generator/id6468916301) from the Apple Store,  to date I have not been able to access the app once.

 I receive the error:

Failed to parse JSONor JWT token missing ( pictured below)

The only option the app offers for me to access and login the [AI EMOJI APP](https://apps.apple.com/us/app/ai-emojis-generator/id6468916301) is through my Apple ID, which is the same email that I used to purchase a subscription so I’m not sure what the issue is.

 I would greatly appreciate if somebody could resolve the matter so then I’m able to access the app. If that’s not possible, I would appreciate it if you could please refund me the full amount of the fee I paid of  $2.95 [per](https://dashboard.stripe.com/receipts/payment/CAcQARoXChVhY2N0XzFPNjdwZkNFQjR6bzliT1Yo1oPtrAYyBgdBupLDrDovFk6SCEA4OLPq71aHkqA91-5cBNem37oBGcwZElwZSiNLoFz9h6fyhdji8l2kR4o) ( attached)  since I have not been able to utilize the application.

[AI Emoji Receipt.pdf](https://github.com/Pondorasti/emojis/files/13855477/AI.Emoji.Receipt.pdf)

![IMG_0959](https://github.com/Pondorasti/emojis/assets/155927083/a8c45e64-655e-408e-8bbf-5161ecef2d7c)

Thank you in advance for your prompt attention and assistance with this matter

April Marie
📧 [aprilmariebee926@gmail.com](mailto:aprilmariebee926@gmail.com)

**Comment by pondorasti** [comment]
resolved over email

**Comment by AlexisMatzopoulos** [comment]
Hi I also get the same error when cloning the repo.
