### ISSUE TITLE
Keep getting this error, dont know whats up. My planetscale url i even hardcoded in the schema in case something was wrong with env variables

### ISSUE THREAD

**Issue by sheel3000** [Pondorasti/emojis#34]
prisma:error 
Invalid `prisma.emoji.count()` invocation:

Error validating datasource `db`: the URL must start with the protocol `[prisma://`](prisma://%60)

 PrismaClientKnownRequestError: 
Invalid `prisma.emoji.count()` invocation:

Error validating datasource `db`: the URL must start with the protocol `prisma://`
    at (node_modules/@prisma/client/runtime/edge.js:85:7234)
    at (node_modules/@prisma/client/runtime/edge.js:85:6567)
    at (node_modules/@prisma/client/runtime/edge.js:85:6253)
    at (node_modules/@prisma/client/runtime/edge.js:90:10066)
    at (src/app/_components/emoji-count/index.tsx:17:16) {
  name: 'PrismaClientKnownRequestError',
  code: 'P6001',
  clientVersion: '5.8.0',
  meta: { modelName: 'Emoji' }
}

**Comment by Olayiwolaaa** [comment]
<div align=center>

## Check your Prisma Client instantiation

<div align=left>

``` javascript
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient({
  datasources: {
    db: process.env.DATABASE_URL,
  },
});
```

``` .env
## Prisma: https://www.prisma.io/docs/reference/database-reference/connection-urls#env
## Set up PlanetScale: https://planetscale.com/docs/tutorials/planetscale-quick-start-guide
DATABASE_URL=prisma://your-database-connection-url
```

<div align=center>

## Verify the datasource configuration

<div align=left>

``` prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL") // make sure this starts with prisma://
}

```

**Comment by pondorasti** [comment]
Thanks for chipping in with the answer @Olayiwolaaa! 🤗

**Comment by iAmCorey** [comment]
> prisma:error Invalid `prisma.emoji.count()` invocation:
> 
> Error validating datasource `db`: the URL must start with the protocol `[prisma://`](prisma://%60)
> 
> PrismaClientKnownRequestError: Invalid `prisma.emoji.count()` invocation:
> 
> Error validating datasource `db`: the URL must start with the protocol `prisma://` at (node_modules/@prisma/client/runtime/edge.js:85:7234) at (node_modules/@prisma/client/runtime/edge.js:85:6567) at (node_modules/@prisma/client/runtime/edge.js:85:6253) at (node_modules/@prisma/client/runtime/edge.js:90:10066) at (src/app/_components/emoji-count/index.tsx:17:16) { name: 'PrismaClientKnownRequestError', code: 'P6001', clientVersion: '5.8.0', meta: { modelName: 'Emoji' } }

meet the same problem, how did you solve it bro?
