### ISSUE TITLE
Unnecessary requests to the API's. 

### ISSUE THREAD

**Issue by shoaibhassan** [Pondorasti/emojis#4]
It's sending a lot of unnecessary requests to the same API even though the response is the same. It also sends requests when the input gains focus.

**Comment by ivancucer** [comment]
Yeah it should be somehow optimised at this point @Pondorasti

**Comment by pondorasti** [comment]
I agree that requests could be a bit better, we are mainly talking about `api/emojis/[id]` endpoint which is cheap. For the time being, I'm going to prioritize https://github.com/Pondorasti/emojis/issues/9 over this.
