### ISSUE TITLE
intercepting routes modal

### ISSUE THREAD

**Issue by euotiniel** [Pondorasti/emojis#9]
add a modal to be able to view the emojis as soon as they are clicked.

**Comment by diomed** [comment]
yes, add an emoji preview, so we can be able to see bigger version before download.
I dont like that we cant open in new tab, without immediately going for download.

**Comment by pondorasti** [comment]
Agreed with both of you. The feature needs to be implemented using [intercepting routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes).
